/**
 * @packageDocumentation
 * @module api.functional._well_known.hp_configuration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { HpConfiguration } from "../../../structures/HpConfiguration";

/**
 * @controller DiscoveryController.getHpConfiguration
 * @path GET /.well-known/hp-configuration
 * @accessor api.functional._well_known.hp_configuration.getHpConfiguration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getHpConfiguration(
  connection: IConnection,
): Promise<getHpConfiguration.Output> {
  return PlainFetcher.fetch(connection, {
    ...getHpConfiguration.METADATA,
    template: getHpConfiguration.METADATA.path,
    path: getHpConfiguration.path(),
  });
}
export namespace getHpConfiguration {
  export type Output = HpConfiguration;

  export const METADATA = {
    method: "GET",
    path: "/.well-known/hp-configuration",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/.well-known/hp-configuration";
}
