/**
 * @packageDocumentation
 * @module api.functional.access.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AccessListResponse } from "../../../structures/AccessListResponse";

/**
 * @controller AccessController.myAccess
 * @path GET /access/me
 * @accessor api.functional.access.me.myAccess
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function myAccess(
  connection: IConnection,
): Promise<myAccess.Output> {
  return PlainFetcher.fetch(connection, {
    ...myAccess.METADATA,
    template: myAccess.METADATA.path,
    path: myAccess.path(),
  });
}
export namespace myAccess {
  export type Output = AccessListResponse;

  export const METADATA = {
    method: "GET",
    path: "/access/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/access/me";
}
