/**
 * @packageDocumentation
 * @module api.functional.auth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthLogoutRequest } from "../../structures/AuthLogoutRequest";
import type { AuthLogoutResponse } from "../../structures/AuthLogoutResponse";
import type { AuthMeResponse } from "../../structures/AuthMeResponse";

/**
 * @controller AuthController.logout
 * @path POST /auth/logout
 * @accessor api.functional.auth.logout
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function logout(
  connection: IConnection,
  body: logout.Body,
): Promise<logout.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...logout.METADATA,
      template: logout.METADATA.path,
      path: logout.path(),
    },
    body,
  );
}
export namespace logout {
  export type Body = AuthLogoutRequest;
  export type Output = AuthLogoutResponse;

  export const METADATA = {
    method: "POST",
    path: "/auth/logout",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/logout";
}

/**
 * @controller AuthController.me
 * @path GET /auth/me
 * @accessor api.functional.auth.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = AuthMeResponse;

  export const METADATA = {
    method: "GET",
    path: "/auth/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/me";
}
