/**
 * @packageDocumentation
 * @module api.functional.access.developer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as accept from "./accept/index";
