/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizationsQuery } from "../structures/AuthorizationsQuery";
import type { AuthorizationsResponse } from "../structures/AuthorizationsResponse";
import type { CredentialsQuery } from "../structures/CredentialsQuery";
import type { CredentialsResponse } from "../structures/CredentialsResponse";

export * as consent from "./consent/index";
export * as presets from "./presets/index";
export * as userinfo from "./userinfo/index";
export * as oauth from "./oauth/index";
export * as _example from "./_example/index";
export * as health from "./health/index";
export * as ready from "./ready/index";
export * as _well_known from "./_well_known/index";
export * as auth from "./auth/index";
export * as access from "./access/index";

/**
 * @controller StatusController.credentials
 * @path GET /credentials
 * @accessor api.functional.credentials
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function credentials(
  connection: IConnection,
  query: credentials.Query,
): Promise<credentials.Output> {
  return PlainFetcher.fetch(connection, {
    ...credentials.METADATA,
    template: credentials.METADATA.path,
    path: credentials.path(query),
  });
}
export namespace credentials {
  export type Query = CredentialsQuery;
  export type Output = CredentialsResponse;

  export const METADATA = {
    method: "GET",
    path: "/credentials",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/credentials";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller StatusController.authorizations
 * @path GET /authorizations
 * @accessor api.functional.authorizations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorizations(
  connection: IConnection,
  query: authorizations.Query,
): Promise<authorizations.Output> {
  return PlainFetcher.fetch(connection, {
    ...authorizations.METADATA,
    template: authorizations.METADATA.path,
    path: authorizations.path(query),
  });
}
export namespace authorizations {
  export type Query = AuthorizationsQuery;
  export type Output = AuthorizationsResponse;

  export const METADATA = {
    method: "GET",
    path: "/authorizations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/authorizations";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
