/**
 * @packageDocumentation
 * @module api.functional._well_known.openid_configuration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { OpenIdConfiguration } from "../../../structures/OpenIdConfiguration";

/**
 * @controller WellKnownController.getOpenIdConfiguration
 * @path GET /.well-known/openid-configuration
 * @accessor api.functional._well_known.openid_configuration.getOpenIdConfiguration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOpenIdConfiguration(
  connection: IConnection,
): Promise<getOpenIdConfiguration.Output> {
  return PlainFetcher.fetch(connection, {
    ...getOpenIdConfiguration.METADATA,
    template: getOpenIdConfiguration.METADATA.path,
    path: getOpenIdConfiguration.path(),
  });
}
export namespace getOpenIdConfiguration {
  export type Output = OpenIdConfiguration;

  export const METADATA = {
    method: "GET",
    path: "/.well-known/openid-configuration",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/.well-known/openid-configuration";
}
