/**
 * @packageDocumentation
 * @module api.functional.oauth.authorize.context
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizeContextQuery } from "../../../../structures/AuthorizeContextQuery";
import type { AuthorizeContextResponse } from "../../../../structures/AuthorizeContextResponse";

/**
 * @controller OauthController.authorizeContext
 * @path GET /oauth/authorize/context
 * @accessor api.functional.oauth.authorize.context.authorizeContext
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorizeContext(
  connection: IConnection,
  query: authorizeContext.Query,
): Promise<authorizeContext.Output> {
  return PlainFetcher.fetch(connection, {
    ...authorizeContext.METADATA,
    template: authorizeContext.METADATA.path,
    path: authorizeContext.path(query),
  });
}
export namespace authorizeContext {
  export type Query = AuthorizeContextQuery;
  export type Output = AuthorizeContextResponse;

  export const METADATA = {
    method: "GET",
    path: "/oauth/authorize/context",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/oauth/authorize/context";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
