/**
 * @packageDocumentation
 * @module api.functional.health
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { HealthLivenessResponse } from "../../structures/HealthLivenessResponse";

/**
 * @controller HealthController.healthcheck
 * @path GET /health
 * @accessor api.functional.health.healthcheck
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function healthcheck(
  connection: IConnection,
): Promise<healthcheck.Output> {
  return PlainFetcher.fetch(connection, {
    ...healthcheck.METADATA,
    template: healthcheck.METADATA.path,
    path: healthcheck.path(),
  });
}
export namespace healthcheck {
  export type Output = HealthLivenessResponse;

  export const METADATA = {
    method: "GET",
    path: "/health",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/health";
}
