/**
 * @packageDocumentation
 * @module api.functional.oauth.client.user_token
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ClientUserTokenRequest } from "../../../../structures/ClientUserTokenRequest";
import type { ClientUserTokenResponse } from "../../../../structures/ClientUserTokenResponse";

/**
 * @controller OauthController.clientUserToken
 * @path POST /oauth/client/user-token
 * @accessor api.functional.oauth.client.user_token.clientUserToken
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function clientUserToken(
  connection: IConnection,
  body: clientUserToken.Body,
): Promise<clientUserToken.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...clientUserToken.METADATA,
      template: clientUserToken.METADATA.path,
      path: clientUserToken.path(),
    },
    body,
  );
}
export namespace clientUserToken {
  export type Body = ClientUserTokenRequest;
  export type Output = ClientUserTokenResponse;

  export const METADATA = {
    method: "POST",
    path: "/oauth/client/user-token",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/oauth/client/user-token";
}
