/**
 * @packageDocumentation
 * @module api.functional.access.requests.standard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { CreateStandardAccessRequestResponse } from "../../../../structures/CreateStandardAccessRequestResponse";

/**
 * @controller AccessController.createStandard
 * @path POST /access/requests/standard
 * @accessor api.functional.access.requests.standard.createStandard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createStandard(
  connection: IConnection,
): Promise<createStandard.Output> {
  return PlainFetcher.fetch(connection, {
    ...createStandard.METADATA,
    template: createStandard.METADATA.path,
    path: createStandard.path(),
  });
}
export namespace createStandard {
  export type Output = CreateStandardAccessRequestResponse;

  export const METADATA = {
    method: "POST",
    path: "/access/requests/standard",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/access/requests/standard";
}
