/**
 * @packageDocumentation
 * @module api.functional.oauth
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { RevokeRequest } from "../../structures/RevokeRequest";
import type { RevokeResponse } from "../../structures/RevokeResponse";
import type { TokenResponse } from "../../structures/TokenResponse";

export * as authorize from "./authorize/index";
export * as client from "./client/index";

/**
 * @controller OauthController.token
 * @path POST /oauth/token
 * @accessor api.functional.oauth.token
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function token(
  connection: IConnection,
  body: token.Body,
): Promise<token.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...token.METADATA,
      template: token.METADATA.path,
      path: token.path(),
    },
    body,
  );
}
export namespace token {
  export type Body =
    | {
        grant_type: "authorization_code";
        code: string;
        redirect_uri: string;
        client_id: string;
        code_verifier: string;
      }
    | {
        grant_type: "refresh_token";
        refresh_token: string;
        client_id: string;
        scope?: undefined | string;
      };
  export type Output = TokenResponse;

  export const METADATA = {
    method: "POST",
    path: "/oauth/token",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/oauth/token";
}

/**
 * @controller OauthController.revoke
 * @path POST /oauth/revoke
 * @accessor api.functional.oauth.revoke
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function revoke(
  connection: IConnection,
  body: revoke.Body,
): Promise<revoke.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...revoke.METADATA,
      template: revoke.METADATA.path,
      path: revoke.path(),
    },
    body,
  );
}
export namespace revoke {
  export type Body = RevokeRequest;
  export type Output = RevokeResponse;

  export const METADATA = {
    method: "POST",
    path: "/oauth/revoke",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/oauth/revoke";
}
