/**
 * @packageDocumentation
 * @module api.functional.access.developer.accept
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AcceptDeveloperRequestBody } from "../../../../structures/AcceptDeveloperRequestBody";
import type { AccessAcceptDeveloperResponse } from "../../../../structures/AccessAcceptDeveloperResponse";

/**
 * @controller AccessController.acceptDeveloper
 * @path POST /access/developer/accept
 * @accessor api.functional.access.developer.accept.acceptDeveloper
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function acceptDeveloper(
  connection: IConnection,
  body: acceptDeveloper.Body,
): Promise<acceptDeveloper.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...acceptDeveloper.METADATA,
      template: acceptDeveloper.METADATA.path,
      path: acceptDeveloper.path(),
    },
    body,
  );
}
export namespace acceptDeveloper {
  export type Body = AcceptDeveloperRequestBody;
  export type Output = AccessAcceptDeveloperResponse;

  export const METADATA = {
    method: "POST",
    path: "/access/developer/accept",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/access/developer/accept";
}
