/**
 * @packageDocumentation
 * @module api.functional.userinfo
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { UserInfoResponse } from "../../structures/UserInfoResponse";

/**
 * @controller UserInfoController.getUserInfo
 * @path GET /userinfo
 * @accessor api.functional.userinfo.getUserInfo
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserInfo(
  connection: IConnection,
): Promise<getUserInfo.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUserInfo.METADATA,
    template: getUserInfo.METADATA.path,
    path: getUserInfo.path(),
  });
}
export namespace getUserInfo {
  export type Output = UserInfoResponse;

  export const METADATA = {
    method: "GET",
    path: "/userinfo",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/userinfo";
}
