/**
 * @packageDocumentation
 * @module api.functional._example
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ExampleEchoRequest } from "../../structures/ExampleEchoRequest";
import type { ExampleEchoResponse } from "../../structures/ExampleEchoResponse";
import type { ExamplePingResponse } from "../../structures/ExamplePingResponse";

/**
 * @controller ExamplesController.ping
 * @path GET /_example/ping
 * @accessor api.functional._example.ping
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function ping(connection: IConnection): Promise<ping.Output> {
  return PlainFetcher.fetch(connection, {
    ...ping.METADATA,
    template: ping.METADATA.path,
    path: ping.path(),
  });
}
export namespace ping {
  export type Output = ExamplePingResponse;

  export const METADATA = {
    method: "GET",
    path: "/_example/ping",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/_example/ping";
}

/**
 * @controller ExamplesController.echo
 * @path POST /_example/echo
 * @accessor api.functional._example.echo
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function echo(
  connection: IConnection,
  body: echo.Body,
): Promise<echo.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...echo.METADATA,
      template: echo.METADATA.path,
      path: echo.path(),
    },
    body,
  );
}
export namespace echo {
  export type Body = ExampleEchoRequest;
  export type Output = ExampleEchoResponse;

  export const METADATA = {
    method: "POST",
    path: "/_example/echo",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/_example/echo";
}
