/**
 * @packageDocumentation
 * @module api.functional.presets
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { PresetResult } from "../../structures/PresetResult";
import type { PresetsListResponse } from "../../structures/PresetsListResponse";
import type { VerifyPresetsRequest } from "../../structures/VerifyPresetsRequest";
import type { VerifyPresetsResponse } from "../../structures/VerifyPresetsResponse";

/**
 * @controller PresetsController.getPreset
 * @path GET /presets/:preset_name
 * @accessor api.functional.presets.getPreset
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getPreset(
  connection: IConnection,
  presetName: string,
): Promise<getPreset.Output> {
  return PlainFetcher.fetch(connection, {
    ...getPreset.METADATA,
    template: getPreset.METADATA.path,
    path: getPreset.path(presetName),
  });
}
export namespace getPreset {
  export type Output = PresetResult;

  export const METADATA = {
    method: "GET",
    path: "/presets/:preset_name",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (presetName: string) =>
    `/presets/${encodeURIComponent(presetName?.toString() ?? "null")}`;
}

/**
 * @controller PresetsController.batch
 * @path POST /presets/batch
 * @accessor api.functional.presets.batch
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function batch(
  connection: IConnection,
  body: batch.Body,
): Promise<batch.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...batch.METADATA,
      template: batch.METADATA.path,
      path: batch.path(),
    },
    body,
  );
}
export namespace batch {
  export type Body = VerifyPresetsRequest;
  export type Output = VerifyPresetsResponse;

  export const METADATA = {
    method: "POST",
    path: "/presets/batch",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/presets/batch";
}

/**
 * @controller PresetsController.list
 * @path GET /presets
 * @accessor api.functional.presets.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function list(connection: IConnection): Promise<list.Output> {
  return PlainFetcher.fetch(connection, {
    ...list.METADATA,
    template: list.METADATA.path,
    path: list.path(),
  });
}
export namespace list {
  export type Output = PresetsListResponse;

  export const METADATA = {
    method: "GET",
    path: "/presets",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/presets";
}
