/**
 * @packageDocumentation
 * @module api.functional.oauth.authorize
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { AuthorizeApproveRequest } from "../../../structures/AuthorizeApproveRequest";
import type { AuthorizeApproveResponse } from "../../../structures/AuthorizeApproveResponse";
import type { AuthorizeQuery } from "../../../structures/AuthorizeQuery";

export * as context from "./context/index";
export * as result from "./result/index";

/**
 * @controller OauthController.authorize
 * @path GET /oauth/authorize
 * @accessor api.functional.oauth.authorize.authorize
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function authorize(
  connection: IConnection,
  query: authorize.Query,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...authorize.METADATA,
    template: authorize.METADATA.path,
    path: authorize.path(query),
  });
}
export namespace authorize {
  export type Query = AuthorizeQuery;

  export const METADATA = {
    method: "GET",
    path: "/oauth/authorize",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/oauth/authorize";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller OauthController.approve
 * @path POST /oauth/authorize/approve
 * @accessor api.functional.oauth.authorize.approve
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function approve(
  connection: IConnection,
  body: approve.Body,
): Promise<approve.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...approve.METADATA,
      template: approve.METADATA.path,
      path: approve.path(),
    },
    body,
  );
}
export namespace approve {
  export type Body = AuthorizeApproveRequest;
  export type Output = AuthorizeApproveResponse;

  export const METADATA = {
    method: "POST",
    path: "/oauth/authorize/approve",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/oauth/authorize/approve";
}
