/**
 * @packageDocumentation
 * @module api.functional._well_known.jwks_json
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { JsonWebKeySet } from "../../../structures/JsonWebKeySet";

/**
 * @controller WellKnownController.getJwks
 * @path GET /.well-known/jwks.json
 * @accessor api.functional._well_known.jwks_json.getJwks
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getJwks(
  connection: IConnection,
): Promise<getJwks.Output> {
  return PlainFetcher.fetch(connection, {
    ...getJwks.METADATA,
    template: getJwks.METADATA.path,
    path: getJwks.path(),
  });
}
export namespace getJwks {
  export type Output = JsonWebKeySet;

  export const METADATA = {
    method: "GET",
    path: "/.well-known/jwks.json",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/.well-known/jwks.json";
}
