/**
 * @packageDocumentation
 * @module api.functional.ready
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { HealthReadinessResponse } from "../../structures/HealthReadinessResponse";

/**
 * @controller HealthController.readiness
 * @path GET /ready
 * @accessor api.functional.ready.readiness
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function readiness(
  connection: IConnection,
): Promise<readiness.Output> {
  return PlainFetcher.fetch(connection, {
    ...readiness.METADATA,
    template: readiness.METADATA.path,
    path: readiness.path(),
  });
}
export namespace readiness {
  export type Output = HealthReadinessResponse;

  export const METADATA = {
    method: "GET",
    path: "/ready",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/ready";
}
