/**
 * @packageDocumentation
 * @module api.functional.consent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as presets from "./presets/index";
