/**
 * @packageDocumentation
 * @module api.functional.consent.presets
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { ConsentPresetsRequest } from "../../../structures/ConsentPresetsRequest";
import type { ConsentPresetsResponse } from "../../../structures/ConsentPresetsResponse";

/**
 * @controller PresetsController.consent
 * @path POST /consent/presets
 * @accessor api.functional.consent.presets.consent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function consent(
  connection: IConnection,
  body: consent.Body,
): Promise<consent.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...consent.METADATA,
      template: consent.METADATA.path,
      path: consent.path(),
    },
    body,
  );
}
export namespace consent {
  export type Body = ConsentPresetsRequest;
  export type Output = ConsentPresetsResponse;

  export const METADATA = {
    method: "POST",
    path: "/consent/presets",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/consent/presets";
}
